/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NFTDutchAuction_ERC20Bids } from "./NFTDutchAuction_ERC20Bids";
export type { YourERC20Token } from "./YourERC20Token";
export type { YourERC721Token } from "./YourERC721Token";
